import ConfigFormInput from './ConfigFormInput.vue';
import FormattedDate from './FormattedDate.vue';
import FormattedTime from './FormattedTime.vue';
import InputCheckbox from './InputCheckbox.vue';
import InputErrors from './InputErrors.vue';
import InputFake from './InputFake.vue';
import InputFile from './InputFile.vue';
import InputFileSimple from './InputFileSimple.vue';
import InputPassword from './InputPassword.vue';
import InputSelect from './InputSelect.vue';
import InputText from './InputText.vue';
import InputTextarea from './InputTextarea.vue';
import SelectAutocomplete from './SelectAutocomplete/index.vue';
import SimplePhotoGallery from './SimplePhotoGallery/index.vue';
import workControls from './work-controls/index.vue';
import wysiwygEditor from './wysiwyg-editor.vue';

export const InputsRegister = (app) => {
    app.component('ConfigFormInput', ConfigFormInput);
    app.component('InputText', InputText);
    app.component('InputFile', InputFile);
    app.component('InputFileSimple', InputFileSimple);
    app.component('InputPassword', InputPassword);
    app.component('InputSelect', InputSelect);
    app.component('InputCheckbox', InputCheckbox);
    app.component('SelectAutocomplete', SelectAutocomplete);
    app.component('InputFake', InputFake);
    app.component('InputTextarea', InputTextarea);
    app.component('InputErrors', InputErrors);
    app.component('SimplePhotoGallery', SimplePhotoGallery);
    app.component('FormattedDate', FormattedDate);
    app.component('wysiwyg-editor', wysiwygEditor);
    app.component('work-controls', workControls);
    app.component('FormattedTime', FormattedTime);
};
